import { href } from "react-router-dom"

export const NavBottomComps=[
    {id:1,item:"Search Galleries and Exhbitions",href:'/'},
    {id:2,item:"Gallery List",href:'gallery-list'},
    {id:3,item:"Exhibiting Artists",href:'#'},
    {id:4,item:"Gallery Maps",href:'#'},
    {id:5,item:"Personal Planner",href:'#'},
    {id:6,item:"Art Fairs",href:'#'},
    {id:7,item:"Art Chauffeurs",href:'#'},
    {id:8,item:"Featured Art For Sale",href:'#'}
]

export const GalleryItems=[
    {
        id:1,
        name:"Lorem Ipsum",
        image:"img1.jpg",
        website:"monyarowegallery.com",
        address:"224 West 30 Street, Suite #304",
        contact_no:"+123 456 7890",
        opening_hours_weekdays:"10.00 - 17.00",
        opening_hours_weekends:"11.00 - 16.00",
        overview:"In this they are to make a type of specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently",
        facebook_url:"#",
        instagram_url:"#",
        location_on_map:"#",
        status:"Open",
        items:[
            {id:1,
            item_name:"IN THE WINDS",
            item_artist:"Emma White",
            item_exhibition_date:"12 June - 18 June",
            item_details:"In this they are to make a type of specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
            item_image:"img2.jpg"
            },
            {id:2,
            item_name:"DARK",
            item_artist:"Emma White",
            item_exhibition_date:"12 June - 18 June",
            item_details:"In this they are to make a type of specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
            item_image:"img3.jpg"
            },
        ],
    },
    {
        id:2,
        name:"Lorem Ipsum",
        image:"img1.jpg",
        website:"monyarowegallery.com",
        address:"224 West 30 Street, Suite #304",
        contact_no:"+123 456 7890",
        opening_hours_weekdays:"10.00 - 17.00",
        opening_hours_weekends:"11.00 - 16.00",
        overview:"In this they are to make a type of specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently",
        facebook_url:"#",
        instagram_url:"#",
        location_on_map:"#",
        status:"Open",
        items:[],
    },
    {
        id:3,
        name:"Lorem Ipsum",
        image:"img1.jpg",
        website:"monyarowegallery.com",
        address:"224 West 30 Street, Suite #304",
        contact_no:"+123 456 7890",
        opening_hours_weekdays:"10.00 - 17.00",
        opening_hours_weekends:"11.00 - 16.00",
        overview:"In this they are to make a type of specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently",
        facebook_url:"#",
        instagram_url:"#",
        location_on_map:"#",
        status:"Closed",
        items:[],
    },
    {
        id:4,
        name:"Lorem Ipsum",
        image:"img1.jpg",
        website:"monyarowegallery.com",
        address:"224 West 30 Street, Suite #304",
        contact_no:"+123 456 7890",
        opening_hours_weekdays:"10.00 - 17.00",
        opening_hours_weekends:"11.00 - 16.00",
        overview:"In this they are to make a type of specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently",
        facebook_url:"#",
        instagram_url:"#",
        location_on_map:"#",
        status:"Open",
        items:[
            {id:1,
            item_name:"IN THE WINDS",
            item_artist:"Emma White",
            item_exhibition_date:"12 June - 18 June",
            item_details:"In this they are to make a type of specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
            item_image:"img2.jpg"
            },
        ],
    },
]

export const GallerylistAlphabets=[
    {id:1,alpha:'a',data:'#'},
    {id:2,alpha:'b',data:'#'},
    {id:3,alpha:'c',data:'#'},
    {id:4,alpha:'d',data:'#'},
    {id:5,alpha:'e',data:'#'},
    {id:6,alpha:'f',data:'#'},
    {id:7,alpha:'g',data:'#'},
    {id:8,alpha:'h',data:'#'},
    {id:9,alpha:'i',data:'#'},
    {id:10,alpha:'j',data:'#'},
    {id:11,alpha:'k',data:'#'},
    {id:12,alpha:'l',data:'#'},
    {id:13,alpha:'m',data:'#'},
    {id:14,alpha:'n',data:'#'},
    {id:15,alpha:'o',data:'#'},
    {id:16,alpha:'p',data:'#'},
    {id:17,alpha:'q',data:'#'},
    {id:18,alpha:'r',data:'#'},
    {id:19,alpha:'s',data:'#'},
    {id:20,alpha:'t',data:'#'},
    {id:21,alpha:'u',data:'#'},
    {id:22,alpha:'v',data:'#'},
    {id:23,alpha:'w',data:'#'},
    {id:24,alpha:'x',data:'#'},
    {id:25,alpha:'y',data:'#'},
    {id:26,alpha:'z',data:'#'},
]

export const defaultGallerylistitems=[
    {id:1,name:"Lorem Ipsum , monyarowegallery.com",href:"/gallery-list-item-details"},
    {id:2,name:"Lorem Ipsum , monyarowegallery.com",href:"/gallery-list-item-details"},
    {id:3,name:"Lorem Ipsum , monyarowegallery.com",href:"/gallery-list-item-details"},
    {id:4,name:"Lorem Ipsum , monyarowegallery.com",href:"/gallery-list-item-details"},
    {id:5,name:"Defiance Gallery at Mary Place",href:"/gallery-list-item-details"},
    {id:6,name:"Lorem Ipsum , monyarowegallery.com",href:"/gallery-list-item-details"},
    {id:7,name:"Lorem Ipsum , monyarowegallery.com",href:"/gallery-list-item-details"},
    {id:8,name:"Lorem Ipsum , monyarowegallery.com",href:"/gallery-list-item-details"},
    {id:9,name:"Lorem Ipsum , monyarowegallery.com",href:"/gallery-list-item-details"},
    {id:10,name:"Lorem Ipsum , monyarowegallery.com",href:"/gallery-list-item-details"},
    {id:11,name:"Lorem Ipsum , monyarowegallery.com",href:"/gallery-list-item-details"},
    {id:12,name:"Lorem Ipsum , monyarowegallery.com",href:"/gallery-list-item-details"},
    {id:13,name:"Lorem Ipsum , monyarowegallery.com",href:"/gallery-list-item-details"},
    {id:14,name:"Lorem Ipsum , monyarowegallery.com",href:"/gallery-list-item-details"},
    {id:15,name:"Lorem Ipsum , monyarowegallery.com",href:"/gallery-list-item-details"},
    {id:16,name:"Lorem Ipsum , monyarowegallery.com",href:"/gallery-list-item-details"},
    {id:17,name:"Dominik Mersch Gallery",href:"/gallery-list-item-details"},
    {id:18,name:"Dickerson Gallery",href:"/gallery-list-item-details"},
    {id:19,name:"Defiance Gallery at Mary Place",href:"/gallery-list-item-details"},
    {id:20,name:"Darren Knight Gallery",href:"/gallery-list-item-details"},
    {id:21,name:"Damien Minton Presents",href:"/gallery-list-item-details"},
    {id:22,name:"D'Lan Contemporary",href:"/gallery-list-item-details"},
    {id:22,name:"Dickerson Gallery",href:"/gallery-list-item-details"},
    {id:22,name:"Dickerson Gallery",href:"/gallery-list-item-details"},
]


export const GalleryItemsDetails=[
    {
        id:1,
        name:"Lorem Ipsum",
        image:"img1.jpg",
        website:"monyarowegallery.com",
        address:"224 West 30 Street, Suite #304",
        contact_no:"+123 456 7890",
        opening_hours_weekdays:"10.00 - 17.00",
        opening_hours_weekends:"11.00 - 16.00",
        overview:"In this they are to make a type of specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ips.en the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsu",
        facebook_url:"#",
        instagram_url:"#",
        location_on_map:"#",
        status:"Open",
        items:[
            {id:1,
            item_name:"IN THE WINDS",
            item_artist:"Emma White",
            item_exhibition_date:"12 June - 18 June",
            item_details:"In this they are to make a type of specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ips.en the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsu",
            item_image:"img2.jpg"
            },
        ],
    },
]